/**
 * LikhaHealth Print Utilities
 * Generates formatted PDF prints and CSV downloads for clinical documentation.
 * 
 * Supported types:
 *  - consultation-summary
 *  - patient-record
 *  - queue-report
 *  - daily-report
 */

// ── Branded Header HTML ──────────────────────────────────────────────────────
function clinicHeader(title, subtitle) {
  return `
    <div style="display:flex; align-items:center; gap:18px; border-bottom:3px solid #0047AB; padding-bottom:14px; margin-bottom:20px">
      <div style="width:56px; height:56px; border-radius:12px; background:linear-gradient(135deg,#0047AB,#1565D8); display:flex; align-items:center; justify-content:center; font-size:26px; color:white; flex-shrink:0">🏥</div>
      <div>
        <div style="font-size:22px; font-weight:700; color:#1a2540; line-height:1.1">
          <span>Likha</span><span style="color:#CC0000">Health</span>
        </div>
        <div style="font-size:13px; color:#7a8fb0; margin-top:2px">Angono Municipal Health Center · Patient Management System</div>
      </div>
      <div style="margin-left:auto; text-align:right">
        <div style="font-size:11px; color:#7a8fb0; text-transform:uppercase; letter-spacing:0.8px">${subtitle || 'Clinical Document'}</div>
        <div style="font-size:16px; font-weight:700; color:#0047AB; margin-top:2px">${title}</div>
      </div>
    </div>
  `;
}

function clinicFooter(staffName) {
  const now = new Date();
  return `
    <div style="margin-top:40px; padding-top:14px; border-top:2px solid #e8edf7; display:flex; justify-content:space-between; color:#7a8fb0; font-size:12px">
      <div>
        <div>Printed on ${now.toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} at ${now.toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit' })}</div>
        <div>Generated by: ${staffName || 'System'}</div>
      </div>
      <div style="text-align:right">
        <div style="font-weight:600; color:#1a2540">LikhaHealth PMS</div>
        <div>Angono, Rizal · Confidential</div>
      </div>
    </div>
  `;
}

function infoRow(label, value) {
  return `
    <div style="display:flex; justify-content:space-between; padding:7px 0; border-bottom:1px solid #f0f3f7">
      <span style="font-size:14px; color:#7a8fb0; text-transform:uppercase; letter-spacing:0.4px">${label}</span>
      <span style="font-size:14px; font-weight:600; color:#1a2540">${value || '—'}</span>
    </div>
  `;
}

function sectionTitle(text) {
  return `<div style="font-size:14px; font-weight:700; color:#0047AB; text-transform:uppercase; letter-spacing:1px; margin:20px 0 10px; border-left:4px solid #0047AB; padding-left:10px">${text}</div>`;
}

function tableHTML(headers, rows) {
  return `
    <table style="width:100%; border-collapse:collapse; margin:10px 0; font-size:14px">
      <thead>
        <tr style="background:#EBF0FA">
          ${headers.map(h => `<th style="padding:8px 12px; text-align:left; font-weight:600; color:#0047AB; border-bottom:2px solid #C0D4F0; font-size:13px; text-transform:uppercase; letter-spacing:0.5px">${h}</th>`).join('')}
        </tr>
      </thead>
      <tbody>
        ${rows.map((row, i) => `
          <tr style="background:${i % 2 === 0 ? 'white' : '#f7f9fd'}">
            ${row.map(cell => `<td style="padding:7px 12px; border-bottom:1px solid #eef1f8; color:#1a2540">${cell ?? '—'}</td>`).join('')}
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
}

// ── PDF via Print ────────────────────────────────────────────────────────────
function openPrintWindow(html) {
  const iframe = document.createElement('iframe');
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  document.body.appendChild(iframe);

  const win = iframe.contentWindow;
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>LikhaHealth Document</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    * { box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; padding: 32px 40px; color: #1a2540; line-height: 1.5; max-width: 900px; margin: 0 auto; }
    @media print {
      body { padding: 20px; }
      @page { margin: 1cm; size: letter; }
    }
  </style>
</head>
<body>${html}</body>
</html>`);
  win.document.close();

  // Brief delay for fonts to load
  setTimeout(() => { 
    win.focus(); 
    win.print(); 
    setTimeout(() => { document.body.removeChild(iframe); }, 1000);
  }, 400);
}

// ── Consultation Summary ─────────────────────────────────────────────────────
export function printConsultationSummary({ patient, diagnosis, notes, vitals, staffName }) {
  let vitalsHTML = '';
  if (vitals) {
    vitalsHTML = sectionTitle('Vitals') + `
      <div style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; margin-bottom:16px">
        ${[
          { label: 'Blood Pressure', value: vitals.bp, unit: 'mmHg' },
          { label: 'Temperature',    value: vitals.temp, unit: '°C' },
          { label: 'Heart Rate',     value: vitals.hr, unit: 'bpm' },
          { label: 'SpO₂',          value: vitals.spo2, unit: '%' },
          { label: 'Weight',         value: vitals.weight, unit: 'kg' },
          { label: 'Height',         value: vitals.height, unit: 'cm' },
        ].map(v => `
          <div style="background:#f7f9fd; border-radius:10px; padding:10px 12px; border:1px solid #e8edf7">
            <div style="font-size:12px; color:#7a8fb0">${v.label}</div>
            <div style="font-size:16px; font-weight:700; color:#1a2540">${v.value ? `${v.value} ${v.unit}` : '—'}</div>
          </div>
        `).join('')}
      </div>
    `;
  }

  const html = `
    ${clinicHeader('Consultation Summary', 'Medical Record')}
    ${sectionTitle('Patient Information')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Patient', patient.name)}
      ${infoRow('Queue Number', patient.queue)}
      ${infoRow('Age', `${patient.age} years`)}
      ${infoRow('Chief Complaint', patient.reason)}
    </div>
    ${vitalsHTML}
    ${sectionTitle('Assessment')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Diagnosis', diagnosis || '(Not recorded)')}
    </div>
    ${sectionTitle("Doctor's Notes")}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; white-space:pre-wrap; font-size:14px; line-height:1.7; color:#1a2540; min-height:80px">
      ${notes || '(No notes recorded)'}
    </div>
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Patient Record ───────────────────────────────────────────────────────────
export function printPatientRecord({ patient, visits, staffName }) {
  const visitsHTML = visits && visits.length > 0
    ? sectionTitle(`Visit History (${visits.length})`) + tableHTML(
        ['Date', 'Queue', 'Reason', 'Diagnosis', 'Doctor'],
        visits.map(v => [
          v.date || v.scheduled_date || '—',
          v.queue || `Q-${String(v.queue_number || 0).padStart(3, '0')}`,
          v.reason || v.visit_reason || '—',
          v.diagnosis || 'Pending',
          v.doctor || v.doctor_name || '—',
        ])
      )
    : '';

  const html = `
    ${clinicHeader('Patient Record', 'Clinical Record')}
    ${sectionTitle('Demographics')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Full Name', patient.name)}
      ${infoRow('Date of Birth', patient.dob || '—')}
      ${infoRow('Age / Sex', `${patient.age || '—'} yrs / ${patient.sex || '—'}`)}
      ${infoRow('Civil Status', patient.civilStatus || '—')}
      ${infoRow('Blood Type', patient.bloodType || '—')}
      ${infoRow('PhilHealth No.', patient.philhealthNo || '—')}
      ${infoRow('Contact', patient.phone || '—')}
      ${infoRow('Address', patient.address || '—')}
      ${infoRow('Emergency Contact', patient.emergencyContact || '—')}
    </div>
    ${visitsHTML}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Queue Report ─────────────────────────────────────────────────────────────
export function printQueueReport({ queue, stats, staffName }) {
  const html = `
    ${clinicHeader('Queue Report', 'Daily Operations')}
    ${sectionTitle('Queue Statistics')}
    <div style="display:grid; grid-template-columns:repeat(5,1fr); gap:10px; margin-bottom:20px">
      ${[
        { label: 'Serving',  value: stats.serving,   color: '#0047AB' },
        { label: 'Waiting',  value: stats.waiting,   color: '#e09040' },
        { label: 'Done',     value: stats.completed, color: '#2a7d5f' },
        { label: 'Skipped',  value: stats.skipped,   color: '#c05080' },
        { label: 'Priority', value: stats.priority,  color: '#8B5FBF' },
      ].map(s => `
        <div style="background:white; border:1px solid #e8edf7; border-radius:12px; padding:14px; text-align:center">
          <div style="font-size:28px; font-weight:700; color:${s.color}">${s.value}</div>
          <div style="font-size:13px; color:#7a8fb0; margin-top:4px">${s.label}</div>
        </div>
      `).join('')}
    </div>
    ${sectionTitle('Queue Entries')}
    ${tableHTML(
      ['Queue #', 'Patient', 'Age', 'Reason', 'Status', 'Arrived'],
      queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.arrived || '—'])
    )}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Daily Report ─────────────────────────────────────────────────────────────
export function printDailyReport({ stats, queue, staffName }) {
  const html = `
    ${clinicHeader('Daily Summary Report', 'Administrative')}
    <div style="font-size:14px; color:#7a8fb0; margin-bottom:20px">
      Report date: ${new Date().toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
    </div>
    ${sectionTitle('Summary Statistics')}
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-bottom:20px">
      ${[
        { label: 'Total Patients',      value: stats.total },
        { label: 'Consultations Done',   value: stats.completed },
        { label: 'Patients Skipped',     value: stats.skipped },
        { label: 'Currently Waiting',    value: stats.waiting },
        { label: 'Priority Patients',    value: stats.priority },
        { label: 'Avg. Wait Time',       value: stats.avgWait || '—' },
      ].map(s => `
        <div style="background:#f7f9fd; border-radius:10px; padding:12px 16px; display:flex; justify-content:space-between; border:1px solid #e8edf7">
          <span style="font-size:14px; color:#7a8fb0">${s.label}</span>
          <span style="font-size:16px; font-weight:700; color:#1a2540">${s.value}</span>
        </div>
      `).join('')}
    </div>
    ${queue && queue.length > 0 ? sectionTitle('Patient Log') + tableHTML(
      ['Queue #', 'Patient', 'Age', 'Reason', 'Status', 'Doctor'],
      queue.map(p => [p.queue, p.name, p.age || '—', p.reason, p.status, p.doctor || '—'])
    ) : ''}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── CSV Download ─────────────────────────────────────────────────────────────
function downloadFile(filename, content, mimeType = 'text/csv;charset=utf-8;') {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeCSV(val) {
  if (val == null) return '';
  const s = String(val);
  return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
}

function toCSV(headers, rows) {
  return [
    headers.join(','),
    ...rows.map(row => row.map(escapeCSV).join(','))
  ].join('\n');
}

export function downloadQueueCSV({ queue, filename }) {
  const csv = toCSV(
    ['Queue Number', 'Patient Name', 'Age', 'Reason for Visit', 'Status', 'Priority', 'Arrived'],
    queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.priority || 'None', p.arrived || ''])
  );
  downloadFile(filename || `queue-report-${new Date().toISOString().slice(0, 10)}.csv`, csv);
}

export function downloadPatientVisitsCSV({ patient, visits, filename }) {
  const csv = toCSV(
    ['Date', 'Queue #', 'Reason', 'Diagnosis', 'Doctor', 'Status'],
    visits.map(v => [
      v.date || v.scheduled_date || '',
      v.queue || '',
      v.reason || v.visit_reason || '',
      v.diagnosis || 'Pending',
      v.doctor || v.doctor_name || '',
      v.status || v.appointment_status || '',
    ])
  );
  downloadFile(filename || `${patient.name.replace(/\s+/g, '_')}_visits_${new Date().toISOString().slice(0, 10)}.csv`, csv);
}

export function downloadDailyReportCSV({ queue, stats, filename }) {
  const summaryRows = [
    ['Total Patients', stats.total],
    ['Completed', stats.completed],
    ['Skipped', stats.skipped],
    ['Waiting', stats.waiting],
    ['Priority', stats.priority],
  ];
  const patientRows = queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.priority || 'None']);

  const csv = [
    'DAILY SUMMARY REPORT',
    `Date,${new Date().toLocaleDateString('en-PH')}`,
    '',
    'Metric,Value',
    ...summaryRows.map(r => r.join(',')),
    '',
    'Queue Number,Patient,Age,Reason,Status,Priority',
    ...patientRows.map(r => r.map(escapeCSV).join(',')),
  ].join('\n');

  downloadFile(filename || `daily-report-${new Date().toISOString().slice(0, 10)}.csv`, csv);
}

// ── Operations Report (Monthly/Weekly) ───────────────────────────────────────
export function printOperationsReport({ period, stats, patientClassification, waitTime, smsDelivery, doctorWorkload, topVisitReasons, staffName }) {
  const periodTitle = period === "month" ? "Monthly" : period === "today" ? "Daily" : "Weekly";
  const reportDate = new Date().toLocaleDateString('en-PH', { month: 'long', year: 'numeric' });
  const smsRate = stats.smsSent + stats.smsFailed > 0 ? Math.round(stats.smsSent / (stats.smsSent + stats.smsFailed) * 100) : 100;
  
  // Patient Classification Table
  const totalClass = patientClassification.reduce((sum, p) => sum + p.value, 0);
  const classRows = patientClassification.map(p => [
    p.name, p.value, totalClass > 0 ? Math.round(p.value / totalClass * 100) + '%' : '0%', '—'
  ]);
  classRows.push(['**Total**', totalClass, '100%', '']);

  // Wait Time Table
  const waitRows = waitTime.map(w => [
    w.day || w.time || w.hour || '—', w.avg, w.peak || '—', w.volume || '—', w.avg <= 30 ? '✅ On Target' : w.avg <= 45 ? '⚠️ Approaching Threshold' : '❌ Exceeded Threshold'
  ]);
  waitRows.push(['**Overall Average**', stats.avgWait, '—', '—', stats.avgWait <= 30 ? '✅ On Target' : stats.avgWait <= 45 ? '⚠️ Approaching Threshold' : '❌ Exceeded Threshold']);

  // SMS Table
  const totalSmsSent = smsDelivery.reduce((s, r) => s + r.sent, 0);
  const totalSmsFailed = smsDelivery.reduce((s, r) => s + r.failed, 0);
  const smsRows = smsDelivery.map(s => {
    const t = s.sent + s.failed;
    const r = t > 0 ? Math.round(s.sent / t * 100) : 100;
    return [s.day || s.category || '—', s.sent, s.failed, r + '%'];
  });
  const overallSmsRate = totalSmsSent + totalSmsFailed > 0 ? Math.round(totalSmsSent / (totalSmsSent + totalSmsFailed) * 100) : 100;
  smsRows.push(['**Total**', totalSmsSent, totalSmsFailed, overallSmsRate + '%']);

  // Doctor Workload
  const docRows = doctorWorkload.map(d => [
    `Dr. ${d.doctor}`, d.patients, '—', d.patients, '—', '—'
  ]);

  // Top Reasons
  const reasonRows = topVisitReasons.slice(0, 10).map((r, i) => [
    i + 1, r.reason, r.count, r.pct + '%', '—'
  ]);

  const html = `
    ${clinicHeader(\`MHC \${periodTitle} Operations Report\`, 'Operations Report')}
    <div style="font-size:14px; color:#1a2540; margin-bottom:20px; background:#f7f9fd; padding:16px; border-radius:12px; border:1px solid #e8edf7">
      <div style="display:flex; justify-content:space-between; margin-bottom:8px"><strong>Report Period:</strong> <span>${periodTitle} — ${reportDate}</span></div>
      <div style="display:flex; justify-content:space-between; margin-bottom:8px"><strong>Prepared by:</strong> <span>${staffName || 'System'} / Administration</span></div>
      <div style="display:flex; justify-content:space-between; margin-bottom:8px"><strong>Date Prepared:</strong> <span>${new Date().toLocaleDateString('en-PH')}</span></div>
      <div style="display:flex; justify-content:space-between"><strong>Reviewed by:</strong> <span>___________________ | <strong>Signature:</strong> ____________</span></div>
    </div>

    ${sectionTitle('SECTION 0 — EXECUTIVE SUMMARY')}
    <div style="display:grid; grid-template-columns:repeat(3, 1fr); gap:12px; margin-bottom:16px">
      ${[
        { label: 'Total Patients', value: stats.total },
        { label: 'Avg. Wait Time', value: stats.avgWait + ' min' },
        { label: 'SMS Delivery Rate', value: smsRate + '%' },
        { label: 'Doctors Active', value: stats.activeDoctors },
        { label: 'Top Visit Reason', value: stats.topReason },
        { label: 'Report Period', value: periodTitle },
      ].map(s => \`
        <div style="background:white; border:1px solid #C0D4F0; border-radius:8px; padding:12px; text-align:center">
          <div style="font-size:12px; color:#7a8fb0; text-transform:uppercase; letter-spacing:0.5px">${s.label}</div>
          <div style="font-size:18px; font-weight:700; color:#0047AB; margin-top:4px">${s.value}</div>
        </div>
      \`).join('')}
    </div>
    <div style="font-size:14px; margin-bottom:20px">
      <p><strong>Summary Narrative:</strong> Overall patient volume was steady for the period. Wait times were managed appropriately. SMS delivery remains reliable. Doctor workload is balanced across available staff.</p>
      <p><strong>Key Highlights:</strong><br/>- Patient queueing flowed without major interruptions.<br/>- SMS reminders successfully reduced skipped appointments.</p>
      <p><strong>Key Concerns / Actions Needed:</strong><br/>- Monitor peak hours to prevent wait times exceeding 45 minutes.</p>
    </div>

    ${sectionTitle('SECTION 1 — PATIENT CLASSIFICATION')}
    ${tableHTML(['Classification', 'No. of Patients', '% Share', 'vs. Prior Period'], classRows)}
    <div style="font-size:13px; color:#4a5d75; margin-bottom:24px"><strong>Analysis & Notes:</strong> Patient composition aligns with expected seasonal volumes. Regular and returning patients constitute the majority.</div>

    ${sectionTitle('SECTION 2 — AVERAGE WAIT TIME')}
    ${tableHTML(['Time Slot / Day', 'Avg Wait (min)', 'Peak Wait (min)', 'Volume', 'Status'], waitRows)}
    <div style="font-size:13px; color:#4a5d75; margin-bottom:24px"><strong>Analysis & Notes:</strong> Wait times are generally within the acceptable threshold.</div>

    ${sectionTitle('SECTION 3 — SMS DELIVERY')}
    ${tableHTML(['SMS Category / Day', 'Sent', 'Failed', 'Delivery Rate'], smsRows)}
    <div style="font-size:13px; color:#4a5d75; margin-bottom:24px"><strong>Analysis & Notes:</strong> High delivery rates indicate stable connectivity and valid patient contact numbers.</div>

    <div style="page-break-before:always;"></div>

    ${sectionTitle('SECTION 4 — DOCTOR WORKLOAD')}
    ${tableHTML(['Doctor / Specialist', 'Avg', 'Weekend', 'Total Consults', 'Avg Duration', 'OT?'], docRows)}
    <div style="font-size:13px; color:#4a5d75; margin-bottom:24px"><strong>Analysis & Notes:</strong> Workload distributed evenly. No capacity concerns flagged for this period.</div>

    ${sectionTitle('SECTION 5 — TOP VISIT REASON')}
    ${tableHTML(['#', 'Visit Reason / Diagnosis', 'No. of Visits', '% of Total', 'Trend vs Prior'], reasonRows)}
    <div style="font-size:13px; color:#4a5d75; margin-bottom:24px"><strong>Analysis & Notes:</strong> Top visit reasons reflect typical primary care trends. Monitor seasonal conditions for potential surges.</div>

    ${sectionTitle('SECTION 6 — OVERALL REMARKS & NEXT STEPS')}
    ${tableHTML(['Area', 'Remarks / Action Items'], [
      ['Highlights', 'Consistent patient flow and low wait times.'],
      ['Concerns', 'None critical at this time.'],
      ['Recommendations', 'Maintain current staffing levels.'],
      ['Next Steps', 'Continue monitoring queue metrics daily.'],
    ])}

    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

export function downloadOperationsReportCSV({ period, stats, patientClassification, waitTime, smsDelivery, doctorWorkload, topVisitReasons }) {
  const periodTitle = period === "month" ? "Monthly" : period === "today" ? "Daily" : "Weekly";
  const reportDate = new Date().toLocaleDateString('en-PH', { month: 'long', year: 'numeric' });
  const smsRate = stats.smsSent + stats.smsFailed > 0 ? Math.round(stats.smsSent / (stats.smsSent + stats.smsFailed) * 100) : 100;

  const totalClass = patientClassification.reduce((sum, p) => sum + p.value, 0);
  const totalSmsSent = smsDelivery.reduce((s, r) => s + r.sent, 0);
  const totalSmsFailed = smsDelivery.reduce((s, r) => s + r.failed, 0);
  const overallSmsRate = totalSmsSent + totalSmsFailed > 0 ? Math.round(totalSmsSent / (totalSmsSent + totalSmsFailed) * 100) : 100;

  const csv = [
    \`MHC \${periodTitle} Operations Report\`,
    \`Report Period: \${periodTitle} - \${reportDate}\`,
    \`Prepared Date: \${new Date().toLocaleDateString('en-PH')}\`,
    '',
    'SECTION 0 — EXECUTIVE SUMMARY',
    'KPI,Value',
    \`Total Patients,\${stats.total}\`,
    \`Avg. Wait Time,\${stats.avgWait} min\`,
    \`SMS Delivery Rate,\${smsRate}%\`,
    \`Doctors Active,\${stats.activeDoctors}\`,
    \`Top Visit Reason,\${escapeCSV(stats.topReason)}\`,
    \`Report Period,\${periodTitle}\`,
    '',
    'SECTION 1 — PATIENT CLASSIFICATION',
    'Classification,No. of Patients,% Share,vs. Prior Month',
    ...patientClassification.map(p => \`\${escapeCSV(p.name)},\${p.value},\${totalClass > 0 ? Math.round(p.value / totalClass * 100) + '%' : '0%'},—\`),
    \`Total,\${totalClass},100%,\`,
    '',
    'SECTION 2 — AVERAGE WAIT TIME',
    'Time Slot / Day,Avg Wait (min),Peak Wait (min),Volume,Status',
    ...waitTime.map(w => \`\${escapeCSV(w.day || w.time || w.hour || '—')},\${w.avg},—,—,\${w.avg <= 30 ? 'On Target' : w.avg <= 45 ? 'Approaching Threshold' : 'Exceeded Threshold'}\`),
    \`Overall Average,\${stats.avgWait},—,—,\${stats.avgWait <= 30 ? 'On Target' : stats.avgWait <= 45 ? 'Approaching Threshold' : 'Exceeded Threshold'}\`,
    '',
    'SECTION 3 — SMS DELIVERY',
    'SMS Category / Day,Sent,Failed,Delivery Rate',
    ...smsDelivery.map(s => {
      const t = s.sent + s.failed;
      const r = t > 0 ? Math.round(s.sent / t * 100) : 100;
      return \`\${escapeCSV(s.day || s.category || '—')},\${s.sent},\${s.failed},\${r}%\`;
    }),
    \`Total,\${totalSmsSent},\${totalSmsFailed},\${overallSmsRate}%\`,
    '',
    'SECTION 4 — DOCTOR WORKLOAD PER MONTH',
    'Doctor / Specialist,Avg,Weekend,Total Consults,Avg Duration,OT?',
    ...doctorWorkload.map(d => \`\${escapeCSV("Dr. " + d.doctor)},\${d.patients},—,\${d.patients},—,—\`),
    '',
    'SECTION 5 — TOP VISIT REASON',
    '#,Visit Reason / Diagnosis,No. of Visits,% of Total,Trend vs Prior',
    ...topVisitReasons.slice(0, 10).map((r, i) => \`\${i + 1},\${escapeCSV(r.reason)},\${r.count},\${r.pct}%,—\`),
    '',
    'SECTION 6 — OVERALL REMARKS & NEXT STEPS',
    'Area,Remarks / Action Items',
    'Highlights,Consistent patient flow and low wait times.',
    'Concerns,None critical at this time.',
    'Recommendations,Maintain current staffing levels.',
    'Next Steps,Continue monitoring queue metrics daily.'
  ].join('\\n');

  downloadFile(\`mhc-\${period}-operations-report-\${new Date().toISOString().slice(0, 10)}.csv\`, csv);
}
