/**
 * LikhaHealth Print Utilities
 * Generates formatted PDF prints and CSV downloads for clinical documentation.
 * 
 * Supported types:
 *  - consultation-summary
 *  - patient-record
 *  - queue-report
 *  - daily-report
 */

// ── Branded Header HTML ──────────────────────────────────────────────────────
function clinicHeader(title, subtitle) {
  return `
    <div style="display:flex; align-items:center; gap:18px; border-bottom:3px solid #0047AB; padding-bottom:14px; margin-bottom:20px">
      <div style="width:56px; height:56px; border-radius:12px; background:linear-gradient(135deg,#0047AB,#1565D8); display:flex; align-items:center; justify-content:center; font-size:26px; color:white; flex-shrink:0">🏥</div>
      <div>
        <div style="font-size:22px; font-weight:700; color:#1a2540; line-height:1.1">
          <span>Likha</span><span style="color:#CC0000">Health</span>
        </div>
        <div style="font-size:13px; color:#7a8fb0; margin-top:2px">Angono Municipal Health Center · Patient Management System</div>
      </div>
      <div style="margin-left:auto; text-align:right">
        <div style="font-size:11px; color:#7a8fb0; text-transform:uppercase; letter-spacing:0.8px">${subtitle || 'Clinical Document'}</div>
        <div style="font-size:16px; font-weight:700; color:#0047AB; margin-top:2px">${title}</div>
      </div>
    </div>
  `;
}

function clinicFooter(staffName) {
  const now = new Date();
  return `
    <div style="margin-top:40px; padding-top:14px; border-top:2px solid #e8edf7; display:flex; justify-content:space-between; color:#7a8fb0; font-size:12px">
      <div>
        <div>Printed on ${now.toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} at ${now.toLocaleTimeString('en-PH', { hour: '2-digit', minute: '2-digit' })}</div>
        <div>Generated by: ${staffName || 'System'}</div>
      </div>
      <div style="text-align:right">
        <div style="font-weight:600; color:#1a2540">LikhaHealth PMS</div>
        <div>Angono, Rizal · Confidential</div>
      </div>
    </div>
  `;
}

function infoRow(label, value) {
  return `
    <div style="display:flex; justify-content:space-between; padding:7px 0; border-bottom:1px solid #f0f3f7">
      <span style="font-size:14px; color:#7a8fb0; text-transform:uppercase; letter-spacing:0.4px">${label}</span>
      <span style="font-size:14px; font-weight:600; color:#1a2540">${value || '—'}</span>
    </div>
  `;
}

function sectionTitle(text) {
  return `<div style="font-size:14px; font-weight:700; color:#0047AB; text-transform:uppercase; letter-spacing:1px; margin:20px 0 10px; border-left:4px solid #0047AB; padding-left:10px">${text}</div>`;
}

function tableHTML(headers, rows) {
  return `
    <table style="width:100%; border-collapse:collapse; margin:10px 0; font-size:14px">
      <thead>
        <tr style="background:#EBF0FA">
          ${headers.map(h => `<th style="padding:8px 12px; text-align:left; font-weight:600; color:#0047AB; border-bottom:2px solid #C0D4F0; font-size:13px; text-transform:uppercase; letter-spacing:0.5px">${h}</th>`).join('')}
        </tr>
      </thead>
      <tbody>
        ${rows.map((row, i) => `
          <tr style="background:${i % 2 === 0 ? 'white' : '#f7f9fd'}">
            ${row.map(cell => `<td style="padding:7px 12px; border-bottom:1px solid #eef1f8; color:#1a2540">${cell ?? '—'}</td>`).join('')}
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
}

// ── PDF via Print ────────────────────────────────────────────────────────────
function openPrintWindow(html) {
  const win = window.open('', '_blank');
  win.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>LikhaHealth Document</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    * { box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; padding: 32px 40px; color: #1a2540; line-height: 1.5; max-width: 900px; margin: 0 auto; }
    @media print {
      body { padding: 20px; }
      @page { margin: 1cm; size: letter; }
    }
  </style>
</head>
<body>${html}</body>
</html>`);
  win.document.close();
  // Brief delay for fonts to load
  setTimeout(() => { win.focus(); win.print(); }, 400);
}

// ── Consultation Summary ─────────────────────────────────────────────────────
export function printConsultationSummary({ patient, diagnosis, notes, vitals, staffName }) {
  let vitalsHTML = '';
  if (vitals) {
    vitalsHTML = sectionTitle('Vitals') + `
      <div style="display:grid; grid-template-columns:1fr 1fr 1fr; gap:10px; margin-bottom:16px">
        ${[
          { label: 'Blood Pressure', value: vitals.bp, unit: 'mmHg' },
          { label: 'Temperature',    value: vitals.temp, unit: '°C' },
          { label: 'Heart Rate',     value: vitals.hr, unit: 'bpm' },
          { label: 'SpO₂',          value: vitals.spo2, unit: '%' },
          { label: 'Weight',         value: vitals.weight, unit: 'kg' },
          { label: 'Height',         value: vitals.height, unit: 'cm' },
        ].map(v => `
          <div style="background:#f7f9fd; border-radius:10px; padding:10px 12px; border:1px solid #e8edf7">
            <div style="font-size:12px; color:#7a8fb0">${v.label}</div>
            <div style="font-size:16px; font-weight:700; color:#1a2540">${v.value ? `${v.value} ${v.unit}` : '—'}</div>
          </div>
        `).join('')}
      </div>
    `;
  }

  const html = `
    ${clinicHeader('Consultation Summary', 'Medical Record')}
    ${sectionTitle('Patient Information')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Patient', patient.name)}
      ${infoRow('Queue Number', patient.queue)}
      ${infoRow('Age', `${patient.age} years`)}
      ${infoRow('Chief Complaint', patient.reason)}
    </div>
    ${vitalsHTML}
    ${sectionTitle('Assessment')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Diagnosis', diagnosis || '(Not recorded)')}
    </div>
    ${sectionTitle("Doctor's Notes")}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; white-space:pre-wrap; font-size:14px; line-height:1.7; color:#1a2540; min-height:80px">
      ${notes || '(No notes recorded)'}
    </div>
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Patient Record ───────────────────────────────────────────────────────────
export function printPatientRecord({ patient, visits, staffName }) {
  const visitsHTML = visits && visits.length > 0
    ? sectionTitle(`Visit History (${visits.length})`) + tableHTML(
        ['Date', 'Queue', 'Reason', 'Diagnosis', 'Doctor'],
        visits.map(v => [
          v.date || v.scheduled_date || '—',
          v.queue || `Q-${String(v.queue_number || 0).padStart(3, '0')}`,
          v.reason || v.visit_reason || '—',
          v.diagnosis || 'Pending',
          v.doctor || v.doctor_name || '—',
        ])
      )
    : '';

  const html = `
    ${clinicHeader('Patient Record', 'Clinical Record')}
    ${sectionTitle('Demographics')}
    <div style="background:#f7f9fd; border-radius:12px; padding:14px 16px; margin-bottom:16px">
      ${infoRow('Full Name', patient.name)}
      ${infoRow('Date of Birth', patient.dob || '—')}
      ${infoRow('Age / Sex', `${patient.age || '—'} yrs / ${patient.sex || '—'}`)}
      ${infoRow('Civil Status', patient.civilStatus || '—')}
      ${infoRow('Blood Type', patient.bloodType || '—')}
      ${infoRow('PhilHealth No.', patient.philhealthNo || '—')}
      ${infoRow('Contact', patient.phone || '—')}
      ${infoRow('Address', patient.address || '—')}
      ${infoRow('Emergency Contact', patient.emergencyContact || '—')}
    </div>
    ${visitsHTML}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Queue Report ─────────────────────────────────────────────────────────────
export function printQueueReport({ queue, stats, staffName }) {
  const html = `
    ${clinicHeader('Queue Report', 'Daily Operations')}
    ${sectionTitle('Queue Statistics')}
    <div style="display:grid; grid-template-columns:repeat(5,1fr); gap:10px; margin-bottom:20px">
      ${[
        { label: 'Serving',  value: stats.serving,   color: '#0047AB' },
        { label: 'Waiting',  value: stats.waiting,   color: '#e09040' },
        { label: 'Done',     value: stats.completed, color: '#2a7d5f' },
        { label: 'Skipped',  value: stats.skipped,   color: '#c05080' },
        { label: 'Priority', value: stats.priority,  color: '#8B5FBF' },
      ].map(s => `
        <div style="background:white; border:1px solid #e8edf7; border-radius:12px; padding:14px; text-align:center">
          <div style="font-size:28px; font-weight:700; color:${s.color}">${s.value}</div>
          <div style="font-size:13px; color:#7a8fb0; margin-top:4px">${s.label}</div>
        </div>
      `).join('')}
    </div>
    ${sectionTitle('Queue Entries')}
    ${tableHTML(
      ['Queue #', 'Patient', 'Age', 'Reason', 'Status', 'Arrived'],
      queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.arrived || '—'])
    )}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── Daily Report ─────────────────────────────────────────────────────────────
export function printDailyReport({ stats, queue, staffName }) {
  const html = `
    ${clinicHeader('Daily Summary Report', 'Administrative')}
    <div style="font-size:14px; color:#7a8fb0; margin-bottom:20px">
      Report date: ${new Date().toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
    </div>
    ${sectionTitle('Summary Statistics')}
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-bottom:20px">
      ${[
        { label: 'Total Patients',      value: stats.total },
        { label: 'Consultations Done',   value: stats.completed },
        { label: 'Patients Skipped',     value: stats.skipped },
        { label: 'Currently Waiting',    value: stats.waiting },
        { label: 'Priority Patients',    value: stats.priority },
        { label: 'Avg. Wait Time',       value: stats.avgWait || '—' },
      ].map(s => `
        <div style="background:#f7f9fd; border-radius:10px; padding:12px 16px; display:flex; justify-content:space-between; border:1px solid #e8edf7">
          <span style="font-size:14px; color:#7a8fb0">${s.label}</span>
          <span style="font-size:16px; font-weight:700; color:#1a2540">${s.value}</span>
        </div>
      `).join('')}
    </div>
    ${queue && queue.length > 0 ? sectionTitle('Patient Log') + tableHTML(
      ['Queue #', 'Patient', 'Age', 'Reason', 'Status', 'Doctor'],
      queue.map(p => [p.queue, p.name, p.age || '—', p.reason, p.status, p.doctor || '—'])
    ) : ''}
    ${clinicFooter(staffName)}
  `;
  openPrintWindow(html);
}

// ── CSV Download ─────────────────────────────────────────────────────────────
function downloadFile(filename, content, mimeType = 'text/csv;charset=utf-8;') {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeCSV(val) {
  if (val == null) return '';
  const s = String(val);
  return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s.replace(/"/g, '""')}"` : s;
}

function toCSV(headers, rows) {
  return [
    headers.join(','),
    ...rows.map(row => row.map(escapeCSV).join(','))
  ].join('\n');
}

export function downloadQueueCSV({ queue, filename }) {
  const csv = toCSV(
    ['Queue Number', 'Patient Name', 'Age', 'Reason for Visit', 'Status', 'Priority', 'Arrived'],
    queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.priority || 'None', p.arrived || ''])
  );
  downloadFile(filename || `queue-report-${new Date().toISOString().slice(0, 10)}.csv`, csv);
}

export function downloadPatientVisitsCSV({ patient, visits, filename }) {
  const csv = toCSV(
    ['Date', 'Queue #', 'Reason', 'Diagnosis', 'Doctor', 'Status'],
    visits.map(v => [
      v.date || v.scheduled_date || '',
      v.queue || '',
      v.reason || v.visit_reason || '',
      v.diagnosis || 'Pending',
      v.doctor || v.doctor_name || '',
      v.status || v.appointment_status || '',
    ])
  );
  downloadFile(filename || `${patient.name.replace(/\s+/g, '_')}_visits_${new Date().toISOString().slice(0, 10)}.csv`, csv);
}

export function downloadDailyReportCSV({ queue, stats, filename }) {
  const summaryRows = [
    ['Total Patients', stats.total],
    ['Completed', stats.completed],
    ['Skipped', stats.skipped],
    ['Waiting', stats.waiting],
    ['Priority', stats.priority],
  ];
  const patientRows = queue.map(p => [p.queue, p.name, p.age, p.reason, p.status, p.priority || 'None']);

  const csv = [
    'DAILY SUMMARY REPORT',
    `Date,${new Date().toLocaleDateString('en-PH')}`,
    '',
    'Metric,Value',
    ...summaryRows.map(r => r.join(',')),
    '',
    'Queue Number,Patient,Age,Reason,Status,Priority',
    ...patientRows.map(r => r.map(escapeCSV).join(',')),
  ].join('\n');

  downloadFile(filename || `daily-report-${new Date().toISOString().slice(0, 10)}.csv`, csv);
}
